Repository python-42/fast-fish, pull requests merged in 2023-05, with the labels that each got.

#8 Implement methods for Card and Deck
  assets/js/Card.js
  assets/js/CardCollection.js
  assets/js/Deck.js
  assets/js/Hand.js
  assets/js/Utils.js
  assets/js/script.js
  assets/ts/Card.ts
  assets/ts/CardCollection.ts
  assets/ts/Deck.ts
  assets/ts/Hand.ts
  assets/ts/Utils.ts
  assets/ts/script.ts
  tsconfig.json
Labels: backend

#12 Moved all UML diagrams into the respective folder
  uml/FRONTEND_TO_BACKEND.md
  uml/GAMEPLAY_SEQUENCE.md
  uml/PLAYER.MD
Labels: cleaning

#14 React Frontend - Workable State
  assets/js/player/ComputerPlayer.js
  assets/ts/cards/CardCollection.ts
  assets/ts/player/ComputerPlayer.ts
  assets/ts/script.ts
  fast-fish/public/images/go-fish.png
  fast-fish/public/images/you_lose.png
  fast-fish/public/images/you_win.png
  fast-fish/src/App.css
  fast-fish/src/BotHand.js
  fast-fish/src/CenterBoard.js
  fast-fish/src/Game.js
  fast-fish/src/GameBoard.js
  fast-fish/src/PlayerHand.js
  fast-fish/src/TurnIcon.js
  fast-fish/src/assets/js/cards/Card.js
  fast-fish/src/assets/js/cards/CardCollection.js
  fast-fish/src/assets/js/cards/Deck.js
  fast-fish/src/assets/js/cards/Hand.js
  fast-fish/src/assets/js/player/ComputerPlayer.js
  fast-fish/src/assets/js/player/HumanPlayer.js
  fast-fish/src/assets/js/player/Player.js
  fast-fish/src/assets/js/script.js
  fast-fish/src/assets/ts/cards/Card.ts
  fast-fish/src/assets/ts/cards/CardCollection.ts
  fast-fish/src/assets/ts/cards/Deck.ts
  fast-fish/src/assets/ts/cards/Hand.ts
  fast-fish/src/assets/ts/player/ComputerPlayer.ts
  fast-fish/src/assets/ts/player/HumanPlayer.ts
  fast-fish/src/assets/ts/player/Player.ts
  fast-fish/src/assets/ts/script.ts
  tsconfig.json
Labels: front-end, react
